### ISSUE TITLE
Request for explanation

### ISSUE THREAD

**Issue by amandesai01** [mjackson/file-storage#2]
I would like to start with how amazing the idea is and how it can impact development speed when implementation details are abstracted away from code. However, question is,
- How is it different from https://github.com/unjs/unstorage ?
- If it is different, can we have a similar API as unstorage so that all the work there is applicable here too?

**Comment by mjackson** [comment]
The main difference here is we are only proposing a storage interface for JS `File` objects. We're not trying to be a one-stop storage for anything at all with different drivers.

That means this library has less responsibility, but can also focus on what it does really well without worrying about supporting any arbitrary type you might want to store.
